### ISSUE TITLE
include python package that is installed locally

### ISSUE THREAD

**Issue by danarte** [zenzire/vimrc#2]
Hi, It's not really an issue with your code but more of a question...
I have a package for python installed locally (I called "python nameOfPackage/setup.py install --user", and it was installed at "~/.local/lib/python2.7/site-packages/HTSeq-0.6.1-py2.7-linux-x86_64.egg/HTSeq/__init__.pyc").
So now I don't know what I need to do to make autocomplete recognize this package.
Do you have any suggestion? maybe add something with setenv? or add something to the PATH ?

Not related to this question, your setup rocks and saved me a lot of time.

**Comment by zenzire** [comment]
Could you please dump and share your environmental variables using command env?

**Comment by danarte** [comment]
Hi, I asked on the jedi [repo page](https://github.com/davidhalter/jedi-vim/issues/600#event-740760862) and it appears they still didn't implement this feature (jedi can't recognize .egg files) though they have this feature in the dev' version and they are planing to add it to the main version of jedi.
Anyway thanks for the interest.
